//
// THIS FILE IS GENERATED, DO NOT MODIFY BY HAND
//
// Use generate.rb to generate when codepoints.txt is updated
//
// Generated on 2016-08-30 15:45:00 +0200
//

import Foundation

@objc public enum MaterialDesignIconFont: Int {
    case accessPoint
    case accessPointNetwork
    case account
    case accountAlert
    case accountBox
    case accountBoxOutline
    case accountCardDetails
    case accountCheck
    case accountCircle
    case accountConvert
    case accountKey
    case accountLocation
    case accountMinus
    case accountMultiple
    case accountMultipleMinus
    case accountMultipleOutline
    case accountMultiplePlus
    case accountNetwork
    case accountOff
    case accountOutline
    case accountPlus
    case accountRemove
    case accountSearch
    case accountSettings
    case accountSettingsVariant
    case accountStar
    case accountStarVariant
    case accountSwitch
    case adjust
    case airConditioner
    case airballoon
    case airplane
    case airplaneLanding
    case airplaneOff
    case airplaneTakeoff
    case airplay
    case alarm
    case alarmCheck
    case alarmMultiple
    case alarmOff
    case alarmPlus
    case alarmSnooze
    case album
    case alert
    case alertBox
    case alertCircle
    case alertCircleOutline
    case alertOctagon
    case alertOutline
    case alpha
    case alphabetical
    case altimeter
    case amazon
    case amazonClouddrive
    case ambulance
    case amplifier
    case anchor
    case android
    case androidDebugBridge
    case androidStudio
    case angular
    case animation
    case apple
    case appleFinder
    case appleIos
    case appleKeyboardCaps
    case appleKeyboardCommand
    case appleKeyboardControl
    case appleKeyboardOption
    case appleKeyboardShift
    case appleMobileme
    case appleSafari
    case application
    case appnet
    case apps
    case archive
    case arrangeBringForward
    case arrangeBringToFront
    case arrangeSendBackward
    case arrangeSendToBack
    case arrowAll
    case arrowBottomLeft
    case arrowBottomRight
    case arrowCompress
    case arrowCompressAll
    case arrowDown
    case arrowDownBold
    case arrowDownBoldCircle
    case arrowDownBoldCircleOutline
    case arrowDownBoldHexagonOutline
    case arrowDownDropCircle
    case arrowDownDropCircleOutline
    case arrowExpand
    case arrowExpandAll
    case arrowLeft
    case arrowLeftBold
    case arrowLeftBoldCircle
    case arrowLeftBoldCircleOutline
    case arrowLeftBoldHexagonOutline
    case arrowLeftDropCircle
    case arrowLeftDropCircleOutline
    case arrowRight
    case arrowRightBold
    case arrowRightBoldCircle
    case arrowRightBoldCircleOutline
    case arrowRightBoldHexagonOutline
    case arrowRightDropCircle
    case arrowRightDropCircleOutline
    case arrowTopLeft
    case arrowTopRight
    case arrowUp
    case arrowUpBold
    case arrowUpBoldCircle
    case arrowUpBoldCircleOutline
    case arrowUpBoldHexagonOutline
    case arrowUpDropCircle
    case arrowUpDropCircleOutline
    case assistant
    case at
    case attachment
    case audiobook
    case autoFix
    case autoUpload
    case autorenew
    case avTimer
    case baby
    case babyBuggy
    case backburger
    case backspace
    case backupRestore
    case bandcamp
    case bank
    case barcode
    case barcodeScan
    case barley
    case barrel
    case basecamp
    case basket
    case basketFill
    case basketUnfill
    case battery
    case battery10
    case battery20
    case battery30
    case battery40
    case battery50
    case battery60
    case battery70
    case battery80
    case battery90
    case batteryAlert
    case batteryCharging
    case batteryCharging100
    case batteryCharging20
    case batteryCharging30
    case batteryCharging40
    case batteryCharging60
    case batteryCharging80
    case batteryCharging90
    case batteryMinus
    case batteryNegative
    case batteryOutline
    case batteryPlus
    case batteryPositive
    case batteryUnknown
    case beach
    case beaker
    case beats
    case beer
    case behance
    case bell
    case bellOff
    case bellOutline
    case bellPlus
    case bellRing
    case bellRingOutline
    case bellSleep
    case beta
    case bible
    case bike
    case bing
    case binoculars
    case bio
    case biohazard
    case bitbucket
    case blackMesa
    case blackberry
    case blender
    case blinds
    case blockHelper
    case blogger
    case bluetooth
    case bluetoothAudio
    case bluetoothConnect
    case bluetoothOff
    case bluetoothSettings
    case bluetoothTransfer
    case blur
    case blurLinear
    case blurOff
    case blurRadial
    case bomb
    case bone
    case book
    case bookMinus
    case bookMultiple
    case bookMultipleVariant
    case bookOpen
    case bookOpenPageVariant
    case bookOpenVariant
    case bookPlus
    case bookVariant
    case bookmark
    case bookmarkCheck
    case bookmarkMusic
    case bookmarkOutline
    case bookmarkPlus
    case bookmarkPlusOutline
    case bookmarkRemove
    case boombox
    case borderAll
    case borderBottom
    case borderColor
    case borderHorizontal
    case borderInside
    case borderLeft
    case borderNone
    case borderOutside
    case borderRight
    case borderStyle
    case borderTop
    case borderVertical
    case bowTie
    case bowl
    case bowling
    case box
    case boxCutter
    case boxShadow
    case bridge
    case briefcase
    case briefcaseCheck
    case briefcaseDownload
    case briefcaseUpload
    case brightness1
    case brightness2
    case brightness3
    case brightness4
    case brightness5
    case brightness6
    case brightness7
    case brightnessAuto
    case broom
    case brush
    case buffer
    case bug
    case bulletinBoard
    case bullhorn
    case bullseye
    case burstMode
    case bus
    case cached
    case cake
    case cakeLayered
    case cakeVariant
    case calculator
    case calendar
    case calendarBlank
    case calendarCheck
    case calendarClock
    case calendarMultiple
    case calendarMultipleCheck
    case calendarPlus
    case calendarQuestion
    case calendarRange
    case calendarRemove
    case calendarText
    case calendarToday
    case callMade
    case callMerge
    case callMissed
    case callReceived
    case callSplit
    case camcorder
    case camcorderBox
    case camcorderBoxOff
    case camcorderOff
    case camera
    case cameraBurst
    case cameraEnhance
    case cameraFront
    case cameraFrontVariant
    case cameraIris
    case cameraOff
    case cameraPartyMode
    case cameraRear
    case cameraRearVariant
    case cameraSwitch
    case cameraTimer
    case candle
    case candycane
    case car
    case carBattery
    case carConnected
    case carWash
    case cards
    case cardsOutline
    case cardsPlayingOutline
    case carrot
    case cart
    case cartOff
    case cartOutline
    case cartPlus
    case caseSensitiveAlt
    case cash
    case cash100
    case cashMultiple
    case cashUsd
    case cast
    case castConnected
    case castle
    case cat
    case cellphone
    case cellphoneAndroid
    case cellphoneBasic
    case cellphoneDock
    case cellphoneIphone
    case cellphoneLink
    case cellphoneLinkOff
    case cellphoneSettings
    case certificate
    case chairSchool
    case chartArc
    case chartAreaspline
    case chartBar
    case chartBubble
    case chartGantt
    case chartHistogram
    case chartLine
    case chartPie
    case chartScatterplotHexbin
    case chartTimeline
    case check
    case checkAll
    case checkCircle
    case checkCircleOutline
    case checkboxBlank
    case checkboxBlankCircle
    case checkboxBlankCircleOutline
    case checkboxBlankOutline
    case checkboxMarked
    case checkboxMarkedCircle
    case checkboxMarkedCircleOutline
    case checkboxMarkedOutline
    case checkboxMultipleBlank
    case checkboxMultipleBlankCircle
    case checkboxMultipleBlankCircleOutline
    case checkboxMultipleBlankOutline
    case checkboxMultipleMarked
    case checkboxMultipleMarkedCircle
    case checkboxMultipleMarkedCircleOutline
    case checkboxMultipleMarkedOutline
    case checkerboard
    case chemicalWeapon
    case chevronDoubleDown
    case chevronDoubleLeft
    case chevronDoubleRight
    case chevronDoubleUp
    case chevronDown
    case chevronLeft
    case chevronRight
    case chevronUp
    case chip
    case church
    case ciscoWebex
    case city
    case clipboard
    case clipboardAccount
    case clipboardAlert
    case clipboardArrowDown
    case clipboardArrowLeft
    case clipboardCheck
    case clipboardOutline
    case clipboardText
    case clippy
    case clock
    case clockAlert
    case clockEnd
    case clockFast
    case clockIn
    case clockOut
    case clockStart
    case close
    case closeBox
    case closeBoxOutline
    case closeCircle
    case closeCircleOutline
    case closeNetwork
    case closeOctagon
    case closeOctagonOutline
    case closedCaption
    case cloud
    case cloudCheck
    case cloudCircle
    case cloudDownload
    case cloudOutline
    case cloudOutlineOff
    case cloudPrint
    case cloudPrintOutline
    case cloudSync
    case cloudUpload
    case codeArray
    case codeBraces
    case codeBrackets
    case codeEqual
    case codeGreaterThan
    case codeGreaterThanOrEqual
    case codeLessThan
    case codeLessThanOrEqual
    case codeNotEqual
    case codeNotEqualVariant
    case codeParentheses
    case codeString
    case codeTags
    case codeTagsCheck
    case codepen
    case coffee
    case coffeeToGo
    case coin
    case coins
    case collage
    case colorHelper
    case comment
    case commentAccount
    case commentAccountOutline
    case commentAlert
    case commentAlertOutline
    case commentCheck
    case commentCheckOutline
    case commentMultipleOutline
    case commentOutline
    case commentPlusOutline
    case commentProcessing
    case commentProcessingOutline
    case commentQuestionOutline
    case commentRemoveOutline
    case commentText
    case commentTextOutline
    case compare
    case compass
    case compassOutline
    case console
    case contactMail
    case contentCopy
    case contentCut
    case contentDuplicate
    case contentPaste
    case contentSave
    case contentSaveAll
    case contentSaveSettings
    case contrast
    case contrastBox
    case contrastCircle
    case cookie
    case copyright
    case counter
    case cow
    case creation
    case creditCard
    case creditCardMultiple
    case creditCardOff
    case creditCardPlus
    case creditCardScan
    case crop
    case cropFree
    case cropLandscape
    case cropPortrait
    case cropRotate
    case cropSquare
    case crosshairs
    case crosshairsGps
    case crown
    case cube
    case cubeOutline
    case cubeSend
    case cubeUnfolded
    case cup
    case cupOff
    case cupWater
    case currencyBtc
    case currencyEur
    case currencyGbp
    case currencyInr
    case currencyNgn
    case currencyRub
    case currencyTry
    case currencyUsd
    case currencyUsdOff
    case cursorDefault
    case cursorDefaultOutline
    case cursorMove
    case cursorPointer
    case cursorText
    case database
    case databaseMinus
    case databasePlus
    case debugStepInto
    case debugStepOut
    case debugStepOver
    case decimalDecrease
    case decimalIncrease
    case delete
    case deleteCircle
    case deleteForever
    case deleteSweep
    case deleteVariant
    case delta
    case deskphone
    case desktopMac
    case desktopTower
    case details
    case developerBoard
    case deviantart
    case dialpad
    case diamond
    case dice1
    case dice2
    case dice3
    case dice4
    case dice5
    case dice6
    case diceD20
    case diceD4
    case diceD6
    case diceD8
    case dictionary
    case directions
    case directionsFork
    case discord
    case disk
    case diskAlert
    case disqus
    case disqusOutline
    case division
    case divisionBox
    case dna
    case dns
    case doNotDisturb
    case doNotDisturbOff
    case dolby
    case domain
    case dotsHorizontal
    case dotsVertical
    case douban
    case download
    case drag
    case dragHorizontal
    case dragVertical
    case drawing
    case drawingBox
    case dribbble
    case dribbbleBox
    case drone
    case dropbox
    case drupal
    case duck
    case dumbbell
    case earth
    case earthOff
    case edge
    case eject
    case elevationDecline
    case elevationRise
    case elevator
    case email
    case emailOpen
    case emailOpenOutline
    case emailOutline
    case emailSecure
    case emailVariant
    case emby
    case emoticon
    case emoticonCool
    case emoticonDead
    case emoticonDevil
    case emoticonExcited
    case emoticonHappy
    case emoticonNeutral
    case emoticonPoop
    case emoticonSad
    case emoticonTongue
    case engine
    case engineOutline
    case equal
    case equalBox
    case eraser
    case eraserVariant
    case escalator
    case ethernet
    case ethernetCable
    case ethernetCableOff
    case etsy
    case evStation
    case evernote
    case exclamation
    case exitToApp
    case export
    case eye
    case eyeOff
    case eyedropper
    case eyedropperVariant
    case face
    case faceProfile
    case facebook
    case facebookBox
    case facebookMessenger
    case factory
    case fan
    case fastForward
    case fax
    case ferry
    case file
    case fileChart
    case fileCheck
    case fileCloud
    case fileDelimited
    case fileDocument
    case fileDocumentBox
    case fileExcel
    case fileExcelBox
    case fileExport
    case fileFind
    case fileHidden
    case fileImage
    case fileImport
    case fileLock
    case fileMultiple
    case fileMusic
    case fileOutline
    case filePdf
    case filePdfBox
    case filePowerpoint
    case filePowerpointBox
    case filePresentationBox
    case fileRestore
    case fileSend
    case fileTree
    case fileVideo
    case fileWord
    case fileWordBox
    case fileXml
    case film
    case filmstrip
    case filmstripOff
    case filter
    case filterOutline
    case filterRemove
    case filterRemoveOutline
    case filterVariant
    case fingerprint
    case fire
    case firefox
    case fish
    case flag
    case flagCheckered
    case flagOutline
    case flagOutlineVariant
    case flagTriangle
    case flagVariant
    case flash
    case flashAuto
    case flashOff
    case flashRedEye
    case flashlight
    case flashlightOff
    case flask
    case flaskEmpty
    case flaskEmptyOutline
    case flaskOutline
    case flattr
    case flipToBack
    case flipToFront
    case floppy
    case flower
    case folder
    case folderAccount
    case folderDownload
    case folderGoogleDrive
    case folderImage
    case folderLock
    case folderLockOpen
    case folderMove
    case folderMultiple
    case folderMultipleImage
    case folderMultipleOutline
    case folderOutline
    case folderPlus
    case folderRemove
    case folderStar
    case folderUpload
    case food
    case foodApple
    case foodForkDrink
    case foodOff
    case foodVariant
    case football
    case footballAustralian
    case footballHelmet
    case formatAlignCenter
    case formatAlignJustify
    case formatAlignLeft
    case formatAlignRight
    case formatAnnotationPlus
    case formatBold
    case formatClear
    case formatColorFill
    case formatColorText
    case formatFloatCenter
    case formatFloatLeft
    case formatFloatNone
    case formatFloatRight
    case formatHeader1
    case formatHeader2
    case formatHeader3
    case formatHeader4
    case formatHeader5
    case formatHeader6
    case formatHeaderDecrease
    case formatHeaderEqual
    case formatHeaderIncrease
    case formatHeaderPound
    case formatHorizontalAlignCenter
    case formatHorizontalAlignLeft
    case formatHorizontalAlignRight
    case formatIndentDecrease
    case formatIndentIncrease
    case formatItalic
    case formatLineSpacing
    case formatLineStyle
    case formatLineWeight
    case formatListBulleted
    case formatListBulletedType
    case formatListNumbers
    case formatPaint
    case formatParagraph
    case formatQuote
    case formatSection
    case formatSize
    case formatStrikethrough
    case formatStrikethroughVariant
    case formatSubscript
    case formatSuperscript
    case formatText
    case formatTextdirectionLToR
    case formatTextdirectionRToL
    case formatTitle
    case formatUnderline
    case formatVerticalAlignBottom
    case formatVerticalAlignCenter
    case formatVerticalAlignTop
    case formatWrapInline
    case formatWrapSquare
    case formatWrapTight
    case formatWrapTopBottom
    case forum
    case forward
    case foursquare
    case fridge
    case fridgeFilled
    case fridgeFilledBottom
    case fridgeFilledTop
    case fullscreen
    case fullscreenExit
    case function
    case gamepad
    case gamepadVariant
    case gasCylinder
    case gasStation
    case gate
    case gauge
    case gavel
    case genderFemale
    case genderMale
    case genderMaleFemale
    case genderTransgender
    case ghost
    case gift
    case git
    case githubBox
    case githubCircle
    case glassFlute
    case glassMug
    case glassStange
    case glassTulip
    case glassdoor
    case glasses
    case gmail
    case gnome
    case gondola
    case google
    case googleCardboard
    case googleChrome
    case googleCircles
    case googleCirclesCommunities
    case googleCirclesExtended
    case googleCirclesGroup
    case googleController
    case googleControllerOff
    case googleDrive
    case googleEarth
    case googleGlass
    case googleMaps
    case googleNearby
    case googlePages
    case googlePhysicalWeb
    case googlePlay
    case googlePlus
    case googlePlusBox
    case googleTranslate
    case googleWallet
    case gradient
    case greasePencil
    case grid
    case gridOff
    case group
    case guitarElectric
    case guitarPick
    case guitarPickOutline
    case hackernews
    case hamburger
    case handPointingRight
    case hanger
    case hangouts
    case harddisk
    case headphones
    case headphonesBox
    case headphonesSettings
    case headset
    case headsetDock
    case headsetOff
    case heart
    case heartBox
    case heartBoxOutline
    case heartBroken
    case heartOutline
    case heartPulse
    case help
    case helpCircle
    case helpCircleOutline
    case hexagon
    case hexagonOutline
    case highway
    case history
    case hololens
    case home
    case homeMapMarker
    case homeModern
    case homeOutline
    case homeVariant
    case hops
    case hospital
    case hospitalBuilding
    case hospitalMarker
    case hotel
    case houzz
    case houzzBox
    case human
    case humanChild
    case humanFemale
    case humanGreeting
    case humanHandsdown
    case humanHandsup
    case humanMale
    case humanMaleFemale
    case humanPregnant
    case image
    case imageAlbum
    case imageArea
    case imageAreaClose
    case imageBroken
    case imageBrokenVariant
    case imageFilter
    case imageFilterBlackWhite
    case imageFilterCenterFocus
    case imageFilterCenterFocusWeak
    case imageFilterDrama
    case imageFilterFrames
    case imageFilterHdr
    case imageFilterNone
    case imageFilterTiltShift
    case imageFilterVintage
    case imageMultiple
    case `import`
    case inbox
    case inboxArrowDown
    case inboxArrowUp
    case incognito
    case information
    case informationOutline
    case informationVariant
    case instagram
    case instapaper
    case internetExplorer
    case invertColors
    case itunes
    case jeepney
    case jira
    case jsfiddle
    case json
    case keg
    case kettle
    case key
    case keyChange
    case keyMinus
    case keyPlus
    case keyRemove
    case keyVariant
    case keyboard
    case keyboardBackspace
    case keyboardCaps
    case keyboardClose
    case keyboardOff
    case keyboardReturn
    case keyboardTab
    case keyboardVariant
    case kodi
    case label
    case labelOutline
    case lambda
    case lamp
    case lan
    case lanConnect
    case lanDisconnect
    case lanPending
    case languageC
    case languageCpp
    case languageCsharp
    case languageCss3
    case languageHtml5
    case languageJavascript
    case languagePhp
    case languagePython
    case languagePythonText
    case laptop
    case laptopChromebook
    case laptopMac
    case laptopWindows
    case lastfm
    case launch
    case layers
    case layersOff
    case leadPencil
    case leaf
    case ledOff
    case ledOn
    case ledOutline
    case ledVariantOff
    case ledVariantOn
    case ledVariantOutline
    case library
    case libraryBooks
    case libraryMusic
    case libraryPlus
    case lightbulb
    case lightbulbOutline
    case link
    case linkOff
    case linkVariant
    case linkVariantOff
    case linkedin
    case linkedinBox
    case linux
    case lock
    case lockOpen
    case lockOpenOutline
    case lockOutline
    case lockPlus
    case login
    case loginVariant
    case logout
    case logoutVariant
    case looks
    case loupe
    case lumx
    case magnet
    case magnetOn
    case magnify
    case magnifyMinus
    case magnifyPlus
    case mailRu
    case map
    case mapMarker
    case mapMarkerCircle
    case mapMarkerMinus
    case mapMarkerMultiple
    case mapMarkerOff
    case mapMarkerPlus
    case mapMarkerRadius
    case margin
    case markdown
    case marker
    case markerCheck
    case martini
    case materialUi
    case mathCompass
    case matrix
    case maxcdn
    case medium
    case memory
    case menu
    case menuDown
    case menuDownOutline
    case menuLeft
    case menuRight
    case menuUp
    case menuUpOutline
    case message
    case messageAlert
    case messageBulleted
    case messageBulletedOff
    case messageDraw
    case messageImage
    case messageOutline
    case messagePlus
    case messageProcessing
    case messageReply
    case messageReplyText
    case messageText
    case messageTextOutline
    case messageVideo
    case meteor
    case microphone
    case microphoneOff
    case microphoneOutline
    case microphoneSettings
    case microphoneVariant
    case microphoneVariantOff
    case microscope
    case microsoft
    case minecraft
    case minus
    case minusBox
    case minusCircle
    case minusCircleOutline
    case minusNetwork
    case mixcloud
    case monitor
    case monitorMultiple
    case more
    case motorbike
    case mouse
    case mouseOff
    case mouseVariant
    case mouseVariantOff
    case moveResize
    case moveResizeVariant
    case movie
    case multiplication
    case multiplicationBox
    case musicBox
    case musicBoxOutline
    case musicCircle
    case musicNote
    case musicNoteBluetooth
    case musicNoteBluetoothOff
    case musicNoteEighth
    case musicNoteHalf
    case musicNoteOff
    case musicNoteQuarter
    case musicNoteSixteenth
    case musicNoteWhole
    case nature
    case naturePeople
    case navigation
    case nearMe
    case needle
    case nestProtect
    case nestThermostat
    case newBox
    case newspaper
    case nfc
    case nfcTap
    case nfcVariant
    case nodejs
    case note
    case noteMultiple
    case noteMultipleOutline
    case noteOutline
    case notePlus
    case notePlusOutline
    case noteText
    case notificationClearAll
    case nuke
    case numeric
    case numeric0Box
    case numeric0BoxMultipleOutline
    case numeric0BoxOutline
    case numeric1Box
    case numeric1BoxMultipleOutline
    case numeric1BoxOutline
    case numeric2Box
    case numeric2BoxMultipleOutline
    case numeric2BoxOutline
    case numeric3Box
    case numeric3BoxMultipleOutline
    case numeric3BoxOutline
    case numeric4Box
    case numeric4BoxMultipleOutline
    case numeric4BoxOutline
    case numeric5Box
    case numeric5BoxMultipleOutline
    case numeric5BoxOutline
    case numeric6Box
    case numeric6BoxMultipleOutline
    case numeric6BoxOutline
    case numeric7Box
    case numeric7BoxMultipleOutline
    case numeric7BoxOutline
    case numeric8Box
    case numeric8BoxMultipleOutline
    case numeric8BoxOutline
    case numeric9Box
    case numeric9BoxMultipleOutline
    case numeric9BoxOutline
    case numeric9PlusBox
    case numeric9PlusBoxMultipleOutline
    case numeric9PlusBoxOutline
    case nutrition
    case oar
    case octagon
    case octagonOutline
    case odnoklassniki
    case office
    case oil
    case oilTemperature
    case omega
    case onedrive
    case opacity
    case openInApp
    case openInNew
    case openid
    case opera
    case ornament
    case ornamentVariant
    case owl
    case package
    case packageDown
    case packageUp
    case packageVariant
    case packageVariantClosed
    case pageFirst
    case pageLast
    case palette
    case paletteAdvanced
    case panda
    case pandora
    case panorama
    case panoramaFisheye
    case panoramaHorizontal
    case panoramaVertical
    case panoramaWideAngle
    case paperCutVertical
    case paperclip
    case parking
    case pause
    case pauseCircle
    case pauseCircleOutline
    case pauseOctagon
    case pauseOctagonOutline
    case paw
    case pawOff
    case pen
    case pencil
    case pencilBox
    case pencilBoxOutline
    case pencilLock
    case pencilOff
    case percent
    case pharmacy
    case phone
    case phoneBluetooth
    case phoneClassic
    case phoneForward
    case phoneHangup
    case phoneInTalk
    case phoneIncoming
    case phoneLocked
    case phoneLog
    case phoneMinus
    case phoneMissed
    case phoneOutgoing
    case phonePaused
    case phonePlus
    case phoneSettings
    case phoneVoip
    case pi
    case piBox
    case piano
    case pig
    case pill
    case pin
    case pinOff
    case pineTree
    case pineTreeBox
    case pinterest
    case pinterestBox
    case pizza
    case planeShield
    case play
    case playBoxOutline
    case playCircle
    case playCircleOutline
    case playPause
    case playProtectedContent
    case playlistCheck
    case playlistMinus
    case playlistPlay
    case playlistPlus
    case playlistRemove
    case playstation
    case plex
    case plus
    case plusBox
    case plusCircle
    case plusCircleMultipleOutline
    case plusCircleOutline
    case plusNetwork
    case plusOne
    case pocket
    case pokeball
    case polaroid
    case poll
    case pollBox
    case polymer
    case pool
    case popcorn
    case pot
    case potMix
    case pound
    case poundBox
    case power
    case powerPlug
    case powerPlugOff
    case powerSettings
    case powerSocket
    case presentation
    case presentationPlay
    case printer
    case printer3d
    case printerAlert
    case priorityHigh
    case priorityLow
    case professionalHexagon
    case projector
    case projectorScreen
    case publish
    case pulse
    case puzzle
    case qqchat
    case qrcode
    case qrcodeScan
    case quadcopter
    case qualityHigh
    case quicktime
    case radar
    case radiator
    case radio
    case radioHandheld
    case radioTower
    case radioactive
    case radioboxBlank
    case radioboxMarked
    case raspberrypi
    case rayEnd
    case rayEndArrow
    case rayStart
    case rayStartArrow
    case rayStartEnd
    case rayVertex
    case rdio
    case read
    case readability
    case receipt
    case record
    case recordRec
    case recycle
    case reddit
    case redo
    case redoVariant
    case refresh
    case regex
    case relativeScale
    case reload
    case remote
    case renameBox
    case reorderHorizontal
    case reorderVertical
    case `repeat`
    case repeatOff
    case repeatOnce
    case replay
    case reply
    case replyAll
    case reproduction
    case resizeBottomRight
    case responsive
    case restore
    case rewind
    case ribbon
    case road
    case roadVariant
    case robot
    case rocket
    case rotate3d
    case rotate90
    case rotateLeft
    case rotateLeftVariant
    case rotateRight
    case rotateRightVariant
    case roundedCorner
    case routerWireless
    case routes
    case rowing
    case rss
    case rssBox
    case ruler
    case run
    case sale
    case satellite
    case satelliteVariant
    case saxophone
    case scale
    case scaleBalance
    case scaleBathroom
    case scanner
    case school
    case screenRotation
    case screenRotationLock
    case screwdriver
    case script
    case sd
    case seal
    case seatFlat
    case seatFlatAngled
    case seatIndividualSuite
    case seatLegroomExtra
    case seatLegroomNormal
    case seatLegroomReduced
    case seatReclineExtra
    case seatReclineNormal
    case security
    case securityHome
    case securityNetwork
    case select
    case selectAll
    case selectInverse
    case selectOff
    case selection
    case send
    case serialPort
    case server
    case serverMinus
    case serverNetwork
    case serverNetworkOff
    case serverOff
    case serverPlus
    case serverRemove
    case serverSecurity
    case settings
    case settingsBox
    case shapeCirclePlus
    case shapePlus
    case shapePolygonPlus
    case shapeRectanglePlus
    case shapeSquarePlus
    case share
    case shareVariant
    case shield
    case shieldOutline
    case shopping
    case shoppingMusic
    case shredder
    case shuffle
    case shuffleDisabled
    case shuffleVariant
    case sigma
    case sigmaLower
    case signCaution
    case signal
    case signalVariant
    case silverware
    case silverwareFork
    case silverwareSpoon
    case silverwareVariant
    case sim
    case simAlert
    case simOff
    case sitemap
    case skipBackward
    case skipForward
    case skipNext
    case skipNextCircle
    case skipNextCircleOutline
    case skipPrevious
    case skipPreviousCircle
    case skipPreviousCircleOutline
    case skull
    case skype
    case skypeBusiness
    case slack
    case sleep
    case sleepOff
    case smoking
    case smokingOff
    case snapchat
    case snowman
    case soccer
    case sofa
    case solid
    case sort
    case sortAlphabetical
    case sortAscending
    case sortDescending
    case sortNumeric
    case sortVariant
    case soundcloud
    case sourceBranch
    case sourceFork
    case sourceMerge
    case sourcePull
    case speaker
    case speakerOff
    case speedometer
    case spellcheck
    case spotify
    case spotlight
    case spotlightBeam
    case spray
    case squareInc
    case squareIncCash
    case stackexchange
    case stackoverflow
    case stairs
    case star
    case starCircle
    case starHalf
    case starOff
    case starOutline
    case steam
    case steering
    case stepBackward
    case stepBackward2
    case stepForward
    case stepForward2
    case stethoscope
    case sticker
    case stocking
    case stop
    case stopCircle
    case stopCircleOutline
    case store
    case store24Hour
    case stove
    case subdirectoryArrowLeft
    case subdirectoryArrowRight
    case subway
    case subwayVariant
    case sunglasses
    case surroundSound
    case swapHorizontal
    case swapVertical
    case swim
    case `switch`
    case sword
    case sync
    case syncAlert
    case syncOff
    case tab
    case tabUnselected
    case table
    case tableColumnPlusAfter
    case tableColumnPlusBefore
    case tableColumnRemove
    case tableColumnWidth
    case tableEdit
    case tableLarge
    case tableRowHeight
    case tableRowPlusAfter
    case tableRowPlusBefore
    case tableRowRemove
    case tablet
    case tabletAndroid
    case tabletIpad
    case tag
    case tagFaces
    case tagHeart
    case tagMultiple
    case tagOutline
    case tagTextOutline
    case target
    case taxi
    case teamviewer
    case telegram
    case television
    case televisionGuide
    case temperatureCelsius
    case temperatureFahrenheit
    case temperatureKelvin
    case tennis
    case tent
    case terrain
    case testTube
    case textShadow
    case textToSpeech
    case textToSpeechOff
    case textbox
    case texture
    case theater
    case themeLightDark
    case thermometer
    case thermometerLines
    case thumbDown
    case thumbDownOutline
    case thumbUp
    case thumbUpOutline
    case thumbsUpDown
    case ticket
    case ticketAccount
    case ticketConfirmation
    case tie
    case timelapse
    case timer
    case timer10
    case timer3
    case timerOff
    case timerSand
    case timerSandEmpty
    case timetable
    case toggleSwitch
    case toggleSwitchOff
    case tooltip
    case tooltipEdit
    case tooltipImage
    case tooltipOutline
    case tooltipOutlinePlus
    case tooltipText
    case tooth
    case tor
    case towerBeach
    case towerFire
    case trafficLight
    case train
    case tram
    case transcribe
    case transcribeClose
    case transfer
    case transitTransfer
    case translate
    case tree
    case trello
    case trendingDown
    case trendingNeutral
    case trendingUp
    case triangle
    case triangleOutline
    case trophy
    case trophyAward
    case trophyOutline
    case trophyVariant
    case trophyVariantOutline
    case truck
    case truckDelivery
    case tshirtCrew
    case tshirtV
    case tumblr
    case tumblrReblog
    case tune
    case tuneVertical
    case twitch
    case twitter
    case twitterBox
    case twitterCircle
    case twitterRetweet
    case ubuntu
    case umbraco
    case umbrella
    case umbrellaOutline
    case undo
    case undoVariant
    case unfoldLess
    case unfoldMore
    case ungroup
    case unity
    case untappd
    case update
    case upload
    case usb
    case vectorArrangeAbove
    case vectorArrangeBelow
    case vectorCircle
    case vectorCircleVariant
    case vectorCombine
    case vectorCurve
    case vectorDifference
    case vectorDifferenceAb
    case vectorDifferenceBa
    case vectorIntersection
    case vectorLine
    case vectorPoint
    case vectorPolygon
    case vectorPolyline
    case vectorRectangle
    case vectorSelection
    case vectorSquare
    case vectorTriangle
    case vectorUnion
    case verified
    case vibrate
    case video
    case videoOff
    case videoSwitch
    case viewAgenda
    case viewArray
    case viewCarousel
    case viewColumn
    case viewDashboard
    case viewDay
    case viewGrid
    case viewHeadline
    case viewList
    case viewModule
    case viewQuilt
    case viewStream
    case viewWeek
    case vimeo
    case vine
    case violin
    case visualstudio
    case vk
    case vkBox
    case vkCircle
    case vlc
    case voice
    case voicemail
    case volumeHigh
    case volumeLow
    case volumeMedium
    case volumeOff
    case vpn
    case walk
    case wallet
    case walletGiftcard
    case walletMembership
    case walletTravel
    case wan
    case watch
    case watchExport
    case watchImport
    case watchVibrate
    case water
    case waterOff
    case waterPercent
    case waterPump
    case watermark
    case weatherCloudy
    case weatherFog
    case weatherHail
    case weatherLightning
    case weatherLightningRainy
    case weatherNight
    case weatherPartlycloudy
    case weatherPouring
    case weatherRainy
    case weatherSnowy
    case weatherSnowyRainy
    case weatherSunny
    case weatherSunset
    case weatherSunsetDown
    case weatherSunsetUp
    case weatherWindy
    case weatherWindyVariant
    case web
    case webcam
    case webhook
    case wechat
    case weight
    case weightKilogram
    case whatsapp
    case wheelchairAccessibility
    case whiteBalanceAuto
    case whiteBalanceIncandescent
    case whiteBalanceIridescent
    case whiteBalanceSunny
    case wifi
    case wifiOff
    case wii
    case wikipedia
    case windowClose
    case windowClosed
    case windowMaximize
    case windowMinimize
    case windowOpen
    case windowRestore
    case windows
    case wordpress
    case worker
    case wrap
    case wrench
    case wunderlist
    case xaml
    case xbox
    case xboxController
    case xboxControllerOff
    case xda
    case xing
    case xingBox
    case xingCircle
    case xml
    case yeast
    case yelp
    case yinYang
    case youtubePlay
    case zipBox
}
internal struct IconFont {
    static let codes = [
        "\u{F002}", "\u{F003}", "\u{F004}", "\u{F005}", "\u{F006}", "\u{F007}", "\u{F5D2}", "\u{F008}", "\u{F009}", "\u{F00A}", "\u{F00B}", "\u{F00C}", "\u{F00D}", "\u{F00E}", "\u{F5D3}", "\u{F00F}", "\u{F010}", "\u{F011}", "\u{F012}", "\u{F013}", "\u{F014}", "\u{F015}", "\u{F016}", "\u{F630}", "\u{F631}", "\u{F017}", "\u{F018}", "\u{F019}", "\u{F01A}", "\u{F01B}", "\u{F01C}", "\u{F01D}", "\u{F5D4}", "\u{F01E}", "\u{F5D5}", "\u{F01F}", "\u{F020}", "\u{F021}", "\u{F022}", "\u{F023}", "\u{F024}", "\u{F68D}", "\u{F025}", "\u{F026}", "\u{F027}", "\u{F028}", "\u{F5D6}", "\u{F029}", "\u{F02A}", "\u{F02B}", "\u{F02C}", "\u{F5D7}", "\u{F02D}", "\u{F02E}", "\u{F02F}", "\u{F030}", "\u{F031}", "\u{F032}", "\u{F033}", "\u{F034}", "\u{F6B1}", "\u{F5D8}", "\u{F035}", "\u{F036}", "\u{F037}", "\u{F632}", "\u{F633}", "\u{F634}", "\u{F635}", "\u{F636}", "\u{F038}", "\u{F039}", "\u{F614}", "\u{F03A}", "\u{F03B}", "\u{F03C}", "\u{F03D}", "\u{F03E}", "\u{F03F}", "\u{F040}", "\u{F041}", "\u{F042}", "\u{F043}", "\u{F615}", "\u{F044}", "\u{F045}", "\u{F046}", "\u{F047}", "\u{F048}", "\u{F049}", "\u{F04A}", "\u{F04B}", "\u{F616}", "\u{F04C}", "\u{F04D}", "\u{F04E}", "\u{F04F}", "\u{F050}", "\u{F051}", "\u{F052}", "\u{F053}", "\u{F054}", "\u{F055}", "\u{F056}", "\u{F057}", "\u{F058}", "\u{F059}", "\u{F05A}", "\u{F05B}", "\u{F05C}", "\u{F05D}", "\u{F05E}", "\u{F05F}", "\u{F060}", "\u{F061}", "\u{F062}", "\u{F063}", "\u{F064}", "\u{F065}", "\u{F066}", "\u{F067}", "\u{F068}", "\u{F069}", "\u{F06A}", "\u{F06B}", "\u{F06C}", "\u{F68E}", "\u{F06D}", "\u{F06E}", "\u{F06F}", "\u{F674}", "\u{F070}", "\u{F071}", "\u{F072}", "\u{F073}", "\u{F074}", "\u{F075}", "\u{F076}", "\u{F077}", "\u{F078}", "\u{F079}", "\u{F07A}", "\u{F07B}", "\u{F07C}", "\u{F07D}", "\u{F07E}", "\u{F07F}", "\u{F080}", "\u{F081}", "\u{F082}", "\u{F083}", "\u{F084}", "\u{F085}", "\u{F086}", "\u{F087}", "\u{F088}", "\u{F089}", "\u{F08A}", "\u{F08B}", "\u{F08C}", "\u{F08D}", "\u{F08E}", "\u{F08F}", "\u{F090}", "\u{F091}", "\u{F092}", "\u{F68F}", "\u{F097}", "\u{F098}", "\u{F099}", "\u{F09A}", "\u{F09B}", "\u{F09C}", "\u{F09D}", "\u{F09E}", "\u{F09F}", "\u{F0A0}", "\u{F0A1}", "\u{F0A2}", "\u{F0A3}", "\u{F0A4}", "\u{F0A5}", "\u{F0A6}", "\u{F0A7}", "\u{F0A8}", "\u{F0A9}", "\u{F0AA}", "\u{F0AB}", "\u{F0AC}", "\u{F0AD}", "\u{F0AE}", "\u{F0AF}", "\u{F0B0}", "\u{F0B1}", "\u{F0B2}", "\u{F0B3}", "\u{F0B4}", "\u{F0B5}", "\u{F0B6}", "\u{F0B7}", "\u{F0B8}", "\u{F690}", "\u{F0B9}", "\u{F0BA}", "\u{F5D9}", "\u{F0BB}", "\u{F0BC}", "\u{F0BD}", "\u{F5DA}", "\u{F0BE}", "\u{F5DB}", "\u{F0BF}", "\u{F0C0}", "\u{F0C1}", "\u{F0C2}", "\u{F0C3}", "\u{F0C5}", "\u{F0C4}", "\u{F0C6}", "\u{F5DC}", "\u{F0C7}", "\u{F0C8}", "\u{F0C9}", "\u{F0CA}", "\u{F0CB}", "\u{F0CC}", "\u{F0CD}", "\u{F0CE}", "\u{F0CF}", "\u{F0D0}", "\u{F0D1}", "\u{F0D2}", "\u{F677}", "\u{F617}", "\u{F0D3}", "\u{F0D4}", "\u{F0D5}", "\u{F637}", "\u{F618}", "\u{F0D6}", "\u{F0D7}", "\u{F0D8}", "\u{F0D9}", "\u{F0DA}", "\u{F0DB}", "\u{F0DC}", "\u{F0DD}", "\u{F0DE}", "\u{F0DF}", "\u{F0E0}", "\u{F0E1}", "\u{F0E2}", "\u{F0E3}", "\u{F619}", "\u{F0E4}", "\u{F0E5}", "\u{F0E6}", "\u{F5DD}", "\u{F5DE}", "\u{F0E7}", "\u{F0E8}", "\u{F0E9}", "\u{F0EA}", "\u{F0EB}", "\u{F0EC}", "\u{F0ED}", "\u{F0EE}", "\u{F0EF}", "\u{F0F0}", "\u{F0F1}", "\u{F0F2}", "\u{F0F3}", "\u{F691}", "\u{F678}", "\u{F0F4}", "\u{F0F5}", "\u{F0F6}", "\u{F0F7}", "\u{F0F8}", "\u{F0F9}", "\u{F0FA}", "\u{F0FB}", "\u{F0FC}", "\u{F0FD}", "\u{F0FE}", "\u{F0FF}", "\u{F100}", "\u{F692}", "\u{F101}", "\u{F102}", "\u{F103}", "\u{F104}", "\u{F5DF}", "\u{F105}", "\u{F106}", "\u{F107}", "\u{F108}", "\u{F109}", "\u{F5E2}", "\u{F10A}", "\u{F10B}", "\u{F10C}", "\u{F10D}", "\u{F10E}", "\u{F638}", "\u{F639}", "\u{F63A}", "\u{F10F}", "\u{F110}", "\u{F66B}", "\u{F111}", "\u{F112}", "\u{F113}", "\u{F114}", "\u{F115}", "\u{F116}", "\u{F117}", "\u{F118}", "\u{F119}", "\u{F11A}", "\u{F11B}", "\u{F11C}", "\u{F11D}", "\u{F11E}", "\u{F11F}", "\u{F120}", "\u{F121}", "\u{F122}", "\u{F123}", "\u{F124}", "\u{F125}", "\u{F126}", "\u{F127}", "\u{F128}", "\u{F5E3}", "\u{F66C}", "\u{F129}", "\u{F12A}", "\u{F12B}", "\u{F66D}", "\u{F66E}", "\u{F12C}", "\u{F12D}", "\u{F5E0}", "\u{F5E1}", "\u{F12E}", "\u{F12F}", "\u{F130}", "\u{F131}", "\u{F132}", "\u{F133}", "\u{F134}", "\u{F135}", "\u{F136}", "\u{F63B}", "\u{F63C}", "\u{F137}", "\u{F138}", "\u{F63D}", "\u{F63E}", "\u{F139}", "\u{F13A}", "\u{F13B}", "\u{F13C}", "\u{F13D}", "\u{F13E}", "\u{F13F}", "\u{F140}", "\u{F141}", "\u{F142}", "\u{F143}", "\u{F61A}", "\u{F144}", "\u{F145}", "\u{F146}", "\u{F147}", "\u{F148}", "\u{F149}", "\u{F14A}", "\u{F14B}", "\u{F14C}", "\u{F14D}", "\u{F14E}", "\u{F14F}", "\u{F150}", "\u{F5CE}", "\u{F151}", "\u{F152}", "\u{F153}", "\u{F154}", "\u{F155}", "\u{F156}", "\u{F157}", "\u{F158}", "\u{F159}", "\u{F15A}", "\u{F15B}", "\u{F15C}", "\u{F15D}", "\u{F15E}", "\u{F15F}", "\u{F160}", "\u{F161}", "\u{F162}", "\u{F163}", "\u{F164}", "\u{F165}", "\u{F166}", "\u{F63F}", "\u{F167}", "\u{F168}", "\u{F169}", "\u{F16A}", "\u{F16B}", "\u{F16C}", "\u{F16D}", "\u{F16E}", "\u{F16F}", "\u{F170}", "\u{F171}", "\u{F172}", "\u{F173}", "\u{F174}", "\u{F693}", "\u{F175}", "\u{F176}", "\u{F177}", "\u{F178}", "\u{F694}", "\u{F640}", "\u{F179}", "\u{F17A}", "\u{F17B}", "\u{F17C}", "\u{F17D}", "\u{F17E}", "\u{F17F}", "\u{F180}", "\u{F181}", "\u{F182}", "\u{F183}", "\u{F184}", "\u{F185}", "\u{F186}", "\u{F187}", "\u{F188}", "\u{F189}", "\u{F18A}", "\u{F18B}", "\u{F18C}", "\u{F18D}", "\u{F18E}", "\u{F18F}", "\u{F190}", "\u{F191}", "\u{F192}", "\u{F193}", "\u{F194}", "\u{F61B}", "\u{F195}", "\u{F196}", "\u{F197}", "\u{F198}", "\u{F5E6}", "\u{F199}", "\u{F19A}", "\u{F1C9}", "\u{F19B}", "\u{F19C}", "\u{F5E4}", "\u{F675}", "\u{F19D}", "\u{F19E}", "\u{F19F}", "\u{F1A0}", "\u{F1A1}", "\u{F695}", "\u{F1A2}", "\u{F1A3}", "\u{F1A4}", "\u{F1A5}", "\u{F1A6}", "\u{F1A7}", "\u{F1A8}", "\u{F1A9}", "\u{F1AA}", "\u{F5E5}", "\u{F1AB}", "\u{F1AC}", "\u{F1AD}", "\u{F1AE}", "\u{F1AF}", "\u{F1B0}", "\u{F1B1}", "\u{F1B2}", "\u{F1B3}", "\u{F679}", "\u{F1B4}", "\u{F1B5}", "\u{F1B6}", "\u{F1B7}", "\u{F5E7}", "\u{F1B8}", "\u{F1B9}", "\u{F1BA}", "\u{F1BB}", "\u{F1BC}", "\u{F1BD}", "\u{F1BE}", "\u{F1BF}", "\u{F1C0}", "\u{F682}", "\u{F5E8}", "\u{F5E9}", "\u{F1C1}", "\u{F1C2}", "\u{F1C3}", "\u{F1C4}", "\u{F1C5}", "\u{F1C6}", "\u{F696}", "\u{F1C7}", "\u{F61C}", "\u{F1C8}", "\u{F1CA}", "\u{F1CB}", "\u{F1CC}", "\u{F1CD}", "\u{F1CE}", "\u{F1CF}", "\u{F5EA}", "\u{F5EB}", "\u{F5EC}", "\u{F5ED}", "\u{F61D}", "\u{F1D0}", "\u{F641}", "\u{F66F}", "\u{F5EE}", "\u{F1D1}", "\u{F1D2}", "\u{F1D3}", "\u{F1D4}", "\u{F1D5}", "\u{F683}", "\u{F1D6}", "\u{F697}", "\u{F698}", "\u{F6B2}", "\u{F1D7}", "\u{F1D8}", "\u{F1D9}", "\u{F699}", "\u{F1DA}", "\u{F1DB}", "\u{F1DC}", "\u{F1DD}", "\u{F1DE}", "\u{F1DF}", "\u{F1E0}", "\u{F1E1}", "\u{F1E2}", "\u{F1E3}", "\u{F1E4}", "\u{F1E5}", "\u{F1E6}", "\u{F1E7}", "\u{F1E8}", "\u{F1E9}", "\u{F1EA}", "\u{F1EB}", "\u{F1EC}", "\u{F1ED}", "\u{F1EE}", "\u{F1EF}", "\u{F5EF}", "\u{F1F0}", "\u{F1F1}", "\u{F5F0}", "\u{F6B3}", "\u{F1F2}", "\u{F1F3}", "\u{F69A}", "\u{F1F4}", "\u{F69B}", "\u{F1F5}", "\u{F1F6}", "\u{F1F7}", "\u{F1F8}", "\u{F1F9}", "\u{F1FA}", "\u{F1FB}", "\u{F1FC}", "\u{F1FD}", "\u{F1FE}", "\u{F642}", "\u{F1FF}", "\u{F200}", "\u{F201}", "\u{F202}", "\u{F203}", "\u{F5F1}", "\u{F204}", "\u{F205}", "\u{F206}", "\u{F207}", "\u{F208}", "\u{F209}", "\u{F20A}", "\u{F20B}", "\u{F643}", "\u{F644}", "\u{F20C}", "\u{F20D}", "\u{F20E}", "\u{F20F}", "\u{F210}", "\u{F211}", "\u{F212}", "\u{F213}", "\u{F214}", "\u{F215}", "\u{F216}", "\u{F217}", "\u{F218}", "\u{F219}", "\u{F21A}", "\u{F21B}", "\u{F21C}", "\u{F21D}", "\u{F21E}", "\u{F613}", "\u{F21F}", "\u{F220}", "\u{F221}", "\u{F222}", "\u{F223}", "\u{F224}", "\u{F225}", "\u{F226}", "\u{F227}", "\u{F228}", "\u{F229}", "\u{F670}", "\u{F22A}", "\u{F645}", "\u{F22B}", "\u{F22C}", "\u{F22D}", "\u{F22E}", "\u{F22F}", "\u{F230}", "\u{F231}", "\u{F232}", "\u{F233}", "\u{F234}", "\u{F235}", "\u{F236}", "\u{F237}", "\u{F238}", "\u{F239}", "\u{F23A}", "\u{F23B}", "\u{F23C}", "\u{F23D}", "\u{F23E}", "\u{F23F}", "\u{F240}", "\u{F241}", "\u{F242}", "\u{F243}", "\u{F67A}", "\u{F244}", "\u{F245}", "\u{F093}", "\u{F094}", "\u{F095}", "\u{F096}", "\u{F246}", "\u{F247}", "\u{F248}", "\u{F249}", "\u{F24A}", "\u{F24B}", "\u{F24C}", "\u{F24D}", "\u{F24E}", "\u{F24F}", "\u{F250}", "\u{F251}", "\u{F252}", "\u{F253}", "\u{F254}", "\u{F255}", "\u{F256}", "\u{F257}", "\u{F258}", "\u{F69C}", "\u{F259}", "\u{F25A}", "\u{F25B}", "\u{F5F2}", "\u{F5F3}", "\u{F25C}", "\u{F25D}", "\u{F25E}", "\u{F25F}", "\u{F260}", "\u{F261}", "\u{F262}", "\u{F263}", "\u{F646}", "\u{F264}", "\u{F265}", "\u{F266}", "\u{F69D}", "\u{F267}", "\u{F268}", "\u{F269}", "\u{F26A}", "\u{F26B}", "\u{F26C}", "\u{F26D}", "\u{F26E}", "\u{F26F}", "\u{F270}", "\u{F271}", "\u{F272}", "\u{F273}", "\u{F274}", "\u{F61E}", "\u{F61F}", "\u{F620}", "\u{F275}", "\u{F276}", "\u{F277}", "\u{F278}", "\u{F5C8}", "\u{F5C9}", "\u{F279}", "\u{F27A}", "\u{F27B}", "\u{F27C}", "\u{F27D}", "\u{F27E}", "\u{F69E}", "\u{F27F}", "\u{F280}", "\u{F281}", "\u{F282}", "\u{F283}", "\u{F284}", "\u{F285}", "\u{F286}", "\u{F5F4}", "\u{F287}", "\u{F621}", "\u{F622}", "\u{F623}", "\u{F288}", "\u{F289}", "\u{F28A}", "\u{F28B}", "\u{F28C}", "\u{F28D}", "\u{F28E}", "\u{F28F}", "\u{F290}", "\u{F291}", "\u{F292}", "\u{F293}", "\u{F294}", "\u{F295}", "\u{F296}", "\u{F297}", "\u{F647}", "\u{F298}", "\u{F299}", "\u{F29A}", "\u{F29B}", "\u{F29C}", "\u{F29D}", "\u{F29E}", "\u{F29F}", "\u{F2A0}", "\u{F2A1}", "\u{F2A2}", "\u{F2A3}", "\u{F2A4}", "\u{F2A5}", "\u{F2A6}", "\u{F2A7}", "\u{F2A8}", "\u{F2A9}", "\u{F2AA}", "\u{F2AB}", "\u{F2AC}", "\u{F685}", "\u{F2AD}", "\u{F2AE}", "\u{F2AF}", "\u{F2B0}", "\u{F2B1}", "\u{F2B2}", "\u{F2B3}", "\u{F2B4}", "\u{F2B5}", "\u{F2B6}", "\u{F2B7}", "\u{F2B8}", "\u{F5F5}", "\u{F2B9}", "\u{F2BA}", "\u{F2BB}", "\u{F2BC}", "\u{F2BD}", "\u{F2BE}", "\u{F2BF}", "\u{F2C0}", "\u{F69F}", "\u{F648}", "\u{F2C1}", "\u{F2C2}", "\u{F2C3}", "\u{F2C4}", "\u{F2C5}", "\u{F2C6}", "\u{F624}", "\u{F684}", "\u{F2C7}", "\u{F2C8}", "\u{F2C9}", "\u{F2CA}", "\u{F2CB}", "\u{F2CC}", "\u{F2CD}", "\u{F2CE}", "\u{F2CF}", "\u{F2D0}", "\u{F2D1}", "\u{F2D2}", "\u{F2D3}", "\u{F2D4}", "\u{F2D5}", "\u{F5F6}", "\u{F2D6}", "\u{F2D7}", "\u{F625}", "\u{F2D8}", "\u{F2D9}", "\u{F5F7}", "\u{F2DA}", "\u{F2DB}", "\u{F2DC}", "\u{F5F8}", "\u{F2DD}", "\u{F6A0}", "\u{F2DE}", "\u{F2DF}", "\u{F2E0}", "\u{F2E1}", "\u{F2E2}", "\u{F2E3}", "\u{F2E4}", "\u{F2E5}", "\u{F2E6}", "\u{F2E7}", "\u{F649}", "\u{F64A}", "\u{F64B}", "\u{F64C}", "\u{F64D}", "\u{F2E8}", "\u{F5CF}", "\u{F2E9}", "\u{F2EA}", "\u{F2EB}", "\u{F2EC}", "\u{F2ED}", "\u{F2EE}", "\u{F2EF}", "\u{F2F0}", "\u{F2F1}", "\u{F2F2}", "\u{F2F3}", "\u{F2F4}", "\u{F2F5}", "\u{F2F6}", "\u{F2F7}", "\u{F2F8}", "\u{F2F9}", "\u{F2FA}", "\u{F686}", "\u{F2FB}", "\u{F3D1}", "\u{F5F9}", "\u{F2FC}", "\u{F2FD}", "\u{F64E}", "\u{F2FE}", "\u{F2FF}", "\u{F300}", "\u{F301}", "\u{F676}", "\u{F302}", "\u{F303}", "\u{F304}", "\u{F626}", "\u{F305}", "\u{F5FA}", "\u{F306}", "\u{F307}", "\u{F308}", "\u{F309}", "\u{F30A}", "\u{F30B}", "\u{F30C}", "\u{F30D}", "\u{F30E}", "\u{F30F}", "\u{F310}", "\u{F311}", "\u{F312}", "\u{F313}", "\u{F314}", "\u{F315}", "\u{F316}", "\u{F627}", "\u{F6B4}", "\u{F317}", "\u{F318}", "\u{F319}", "\u{F31A}", "\u{F671}", "\u{F672}", "\u{F31B}", "\u{F31C}", "\u{F31D}", "\u{F31E}", "\u{F31F}", "\u{F320}", "\u{F321}", "\u{F322}", "\u{F323}", "\u{F324}", "\u{F325}", "\u{F326}", "\u{F327}", "\u{F328}", "\u{F329}", "\u{F64F}", "\u{F32A}", "\u{F32B}", "\u{F32C}", "\u{F32D}", "\u{F32E}", "\u{F32F}", "\u{F330}", "\u{F331}", "\u{F332}", "\u{F333}", "\u{F334}", "\u{F335}", "\u{F336}", "\u{F337}", "\u{F338}", "\u{F339}", "\u{F33A}", "\u{F33B}", "\u{F33C}", "\u{F33D}", "\u{F33E}", "\u{F33F}", "\u{F340}", "\u{F341}", "\u{F5FB}", "\u{F342}", "\u{F5FC}", "\u{F343}", "\u{F5FD}", "\u{F344}", "\u{F345}", "\u{F346}", "\u{F347}", "\u{F348}", "\u{F349}", "\u{F34A}", "\u{F34B}", "\u{F34C}", "\u{F34D}", "\u{F34E}", "\u{F34F}", "\u{F650}", "\u{F350}", "\u{F351}", "\u{F651}", "\u{F352}", "\u{F353}", "\u{F354}", "\u{F652}", "\u{F355}", "\u{F356}", "\u{F357}", "\u{F358}", "\u{F628}", "\u{F359}", "\u{F35A}", "\u{F35B}", "\u{F35C}", "\u{F35D}", "\u{F6B5}", "\u{F35E}", "\u{F35F}", "\u{F360}", "\u{F6B6}", "\u{F361}", "\u{F362}", "\u{F6A1}", "\u{F6A2}", "\u{F363}", "\u{F364}", "\u{F365}", "\u{F653}", "\u{F366}", "\u{F367}", "\u{F368}", "\u{F369}", "\u{F36A}", "\u{F36B}", "\u{F629}", "\u{F36C}", "\u{F36D}", "\u{F36E}", "\u{F36F}", "\u{F370}", "\u{F371}", "\u{F654}", "\u{F372}", "\u{F373}", "\u{F374}", "\u{F375}", "\u{F376}", "\u{F377}", "\u{F378}", "\u{F62A}", "\u{F379}", "\u{F37A}", "\u{F37B}", "\u{F37C}", "\u{F37D}", "\u{F37E}", "\u{F37F}", "\u{F380}", "\u{F655}", "\u{F656}", "\u{F381}", "\u{F382}", "\u{F383}", "\u{F384}", "\u{F385}", "\u{F386}", "\u{F387}", "\u{F5FE}", "\u{F5FF}", "\u{F388}", "\u{F389}", "\u{F38A}", "\u{F38B}", "\u{F38C}", "\u{F38D}", "\u{F38E}", "\u{F38F}", "\u{F390}", "\u{F5CD}", "\u{F391}", "\u{F392}", "\u{F393}", "\u{F394}", "\u{F395}", "\u{F396}", "\u{F397}", "\u{F398}", "\u{F399}", "\u{F39A}", "\u{F6B7}", "\u{F6B8}", "\u{F39B}", "\u{F39C}", "\u{F39D}", "\u{F39E}", "\u{F39F}", "\u{F6A3}", "\u{F3A0}", "\u{F3A1}", "\u{F3A2}", "\u{F3A3}", "\u{F3A4}", "\u{F3A5}", "\u{F3A6}", "\u{F3A7}", "\u{F3A8}", "\u{F3A9}", "\u{F3AA}", "\u{F3AB}", "\u{F3AC}", "\u{F3AD}", "\u{F3AE}", "\u{F3AF}", "\u{F3B0}", "\u{F3B1}", "\u{F3B2}", "\u{F3B3}", "\u{F3B4}", "\u{F3B5}", "\u{F3B6}", "\u{F3B7}", "\u{F3B8}", "\u{F3B9}", "\u{F3BA}", "\u{F3BB}", "\u{F3BC}", "\u{F3BD}", "\u{F3BE}", "\u{F3BF}", "\u{F3C0}", "\u{F3C1}", "\u{F3C2}", "\u{F67B}", "\u{F3C3}", "\u{F3C4}", "\u{F3C5}", "\u{F3C6}", "\u{F3C7}", "\u{F3C8}", "\u{F3C9}", "\u{F3CA}", "\u{F5CC}", "\u{F3CB}", "\u{F3CC}", "\u{F3CD}", "\u{F3CE}", "\u{F3CF}", "\u{F3D0}", "\u{F3D2}", "\u{F3D3}", "\u{F3D4}", "\u{F3D5}", "\u{F3D6}", "\u{F3D7}", "\u{F600}", "\u{F601}", "\u{F3D8}", "\u{F3D9}", "\u{F3DA}", "\u{F3DB}", "\u{F3DC}", "\u{F3DD}", "\u{F3DE}", "\u{F3DF}", "\u{F3E0}", "\u{F3E1}", "\u{F3E2}", "\u{F3E3}", "\u{F3E4}", "\u{F3E5}", "\u{F3E6}", "\u{F3E7}", "\u{F3E8}", "\u{F3E9}", "\u{F657}", "\u{F3EA}", "\u{F3EB}", "\u{F3EC}", "\u{F3ED}", "\u{F3EE}", "\u{F3EF}", "\u{F3F0}", "\u{F3F1}", "\u{F3F2}", "\u{F3F3}", "\u{F602}", "\u{F3F4}", "\u{F3F5}", "\u{F3F6}", "\u{F3F7}", "\u{F3F8}", "\u{F3F9}", "\u{F658}", "\u{F3FA}", "\u{F3FB}", "\u{F3FC}", "\u{F659}", "\u{F3FD}", "\u{F3FE}", "\u{F3FF}", "\u{F400}", "\u{F67C}", "\u{F401}", "\u{F402}", "\u{F403}", "\u{F404}", "\u{F405}", "\u{F406}", "\u{F407}", "\u{F408}", "\u{F409}", "\u{F6BA}", "\u{F40A}", "\u{F40B}", "\u{F40C}", "\u{F40D}", "\u{F40E}", "\u{F40F}", "\u{F5C7}", "\u{F410}", "\u{F411}", "\u{F412}", "\u{F413}", "\u{F414}", "\u{F6B9}", "\u{F415}", "\u{F416}", "\u{F417}", "\u{F418}", "\u{F419}", "\u{F41A}", "\u{F41B}", "\u{F41C}", "\u{F41D}", "\u{F41E}", "\u{F41F}", "\u{F420}", "\u{F421}", "\u{F606}", "\u{F422}", "\u{F65A}", "\u{F65B}", "\u{F423}", "\u{F424}", "\u{F425}", "\u{F6A4}", "\u{F6A5}", "\u{F426}", "\u{F427}", "\u{F428}", "\u{F429}", "\u{F42A}", "\u{F42B}", "\u{F42C}", "\u{F603}", "\u{F604}", "\u{F42D}", "\u{F42E}", "\u{F42F}", "\u{F6A6}", "\u{F430}", "\u{F431}", "\u{F605}", "\u{F432}", "\u{F433}", "\u{F434}", "\u{F435}", "\u{F436}", "\u{F437}", "\u{F438}", "\u{F439}", "\u{F43A}", "\u{F43B}", "\u{F43C}", "\u{F43D}", "\u{F43E}", "\u{F43F}", "\u{F440}", "\u{F441}", "\u{F442}", "\u{F443}", "\u{F444}", "\u{F445}", "\u{F446}", "\u{F447}", "\u{F448}", "\u{F449}", "\u{F44A}", "\u{F44B}", "\u{F44C}", "\u{F44D}", "\u{F44E}", "\u{F44F}", "\u{F450}", "\u{F451}", "\u{F452}", "\u{F453}", "\u{F454}", "\u{F455}", "\u{F687}", "\u{F688}", "\u{F456}", "\u{F457}", "\u{F458}", "\u{F459}", "\u{F45A}", "\u{F45B}", "\u{F45C}", "\u{F45D}", "\u{F45E}", "\u{F6A7}", "\u{F45F}", "\u{F460}", "\u{F461}", "\u{F462}", "\u{F6A8}", "\u{F463}", "\u{F464}", "\u{F6A9}", "\u{F465}", "\u{F466}", "\u{F467}", "\u{F468}", "\u{F607}", "\u{F469}", "\u{F46A}", "\u{F608}", "\u{F46B}", "\u{F46C}", "\u{F46D}", "\u{F46E}", "\u{F46F}", "\u{F470}", "\u{F471}", "\u{F609}", "\u{F472}", "\u{F5D1}", "\u{F473}", "\u{F6AA}", "\u{F474}", "\u{F475}", "\u{F476}", "\u{F477}", "\u{F478}", "\u{F479}", "\u{F47A}", "\u{F47B}", "\u{F47C}", "\u{F47D}", "\u{F47E}", "\u{F47F}", "\u{F480}", "\u{F481}", "\u{F482}", "\u{F483}", "\u{F689}", "\u{F484}", "\u{F485}", "\u{F486}", "\u{F487}", "\u{F488}", "\u{F489}", "\u{F48A}", "\u{F65C}", "\u{F48B}", "\u{F48C}", "\u{F48D}", "\u{F48E}", "\u{F48F}", "\u{F490}", "\u{F491}", "\u{F492}", "\u{F493}", "\u{F494}", "\u{F65D}", "\u{F495}", "\u{F65E}", "\u{F65F}", "\u{F660}", "\u{F496}", "\u{F497}", "\u{F498}", "\u{F499}", "\u{F49A}", "\u{F49B}", "\u{F49C}", "\u{F49D}", "\u{F49E}", "\u{F49F}", "\u{F4A0}", "\u{F62B}", "\u{F4A1}", "\u{F4A2}", "\u{F60A}", "\u{F4A3}", "\u{F4A4}", "\u{F4A5}", "\u{F4A6}", "\u{F4A7}", "\u{F4A8}", "\u{F4A9}", "\u{F4AA}", "\u{F4AB}", "\u{F4AC}", "\u{F4AD}", "\u{F661}", "\u{F662}", "\u{F4AE}", "\u{F663}", "\u{F664}", "\u{F68B}", "\u{F4AF}", "\u{F4B0}", "\u{F4B1}", "\u{F4B2}", "\u{F4B3}", "\u{F4B4}", "\u{F4B5}", "\u{F4B6}", "\u{F4B7}", "\u{F4B8}", "\u{F4B9}", "\u{F68C}", "\u{F4BA}", "\u{F4BB}", "\u{F4BC}", "\u{F4BD}", "\u{F4BE}", "\u{F4BF}", "\u{F4C0}", "\u{F62C}", "\u{F4C1}", "\u{F62D}", "\u{F4C2}", "\u{F4C3}", "\u{F4C4}", "\u{F4C5}", "\u{F4C6}", "\u{F4C7}", "\u{F4C8}", "\u{F4C9}", "\u{F665}", "\u{F4CA}", "\u{F4CB}", "\u{F60B}", "\u{F4CC}", "\u{F4CD}", "\u{F4CE}", "\u{F4CF}", "\u{F4D0}", "\u{F4D1}", "\u{F4D2}", "\u{F4D3}", "\u{F4D4}", "\u{F4D5}", "\u{F4D6}", "\u{F4D7}", "\u{F4D8}", "\u{F4D9}", "\u{F5D0}", "\u{F4DA}", "\u{F4DB}", "\u{F666}", "\u{F667}", "\u{F4DC}", "\u{F4DD}", "\u{F4DE}", "\u{F60C}", "\u{F60D}", "\u{F6AB}", "\u{F4DF}", "\u{F4E0}", "\u{F5C5}", "\u{F4E1}", "\u{F4E2}", "\u{F4E3}", "\u{F4E4}", "\u{F4E5}", "\u{F4E6}", "\u{F4E7}", "\u{F4E8}", "\u{F4E9}", "\u{F4EA}", "\u{F4EB}", "\u{F4EC}", "\u{F4ED}", "\u{F4EE}", "\u{F4EF}", "\u{F4F0}", "\u{F4F1}", "\u{F4F2}", "\u{F4F3}", "\u{F4F4}", "\u{F4F5}", "\u{F4F6}", "\u{F4F7}", "\u{F4F8}", "\u{F4F9}", "\u{F4FA}", "\u{F68A}", "\u{F4FB}", "\u{F4FC}", "\u{F4FD}", "\u{F4FE}", "\u{F4FF}", "\u{F500}", "\u{F501}", "\u{F502}", "\u{F503}", "\u{F504}", "\u{F505}", "\u{F506}", "\u{F507}", "\u{F508}", "\u{F509}", "\u{F668}", "\u{F669}", "\u{F50A}", "\u{F50B}", "\u{F60E}", "\u{F50C}", "\u{F50D}", "\u{F50E}", "\u{F50F}", "\u{F510}", "\u{F511}", "\u{F512}", "\u{F513}", "\u{F514}", "\u{F515}", "\u{F516}", "\u{F517}", "\u{F518}", "\u{F519}", "\u{F51A}", "\u{F51B}", "\u{F51C}", "\u{F51D}", "\u{F51E}", "\u{F51F}", "\u{F6AC}", "\u{F520}", "\u{F521}", "\u{F522}", "\u{F523}", "\u{F524}", "\u{F525}", "\u{F526}", "\u{F527}", "\u{F528}", "\u{F529}", "\u{F52A}", "\u{F680}", "\u{F681}", "\u{F52B}", "\u{F52C}", "\u{F52D}", "\u{F52E}", "\u{F52F}", "\u{F530}", "\u{F6AD}", "\u{F5CA}", "\u{F531}", "\u{F532}", "\u{F533}", "\u{F534}", "\u{F535}", "\u{F536}", "\u{F537}", "\u{F538}", "\u{F539}", "\u{F53A}", "\u{F53B}", "\u{F53C}", "\u{F53D}", "\u{F53E}", "\u{F53F}", "\u{F540}", "\u{F541}", "\u{F542}", "\u{F62E}", "\u{F66A}", "\u{F543}", "\u{F544}", "\u{F545}", "\u{F546}", "\u{F547}", "\u{F548}", "\u{F549}", "\u{F54A}", "\u{F54B}", "\u{F54C}", "\u{F54D}", "\u{F54E}", "\u{F54F}", "\u{F550}", "\u{F6AE}", "\u{F551}", "\u{F6AF}", "\u{F552}", "\u{F553}", "\u{F554}", "\u{F555}", "\u{F556}", "\u{F557}", "\u{F558}", "\u{F559}", "\u{F55A}", "\u{F55B}", "\u{F55C}", "\u{F55D}", "\u{F55E}", "\u{F55F}", "\u{F560}", "\u{F561}", "\u{F5C6}", "\u{F562}", "\u{F001}", "\u{F563}", "\u{F564}", "\u{F565}", "\u{F566}", "\u{F567}", "\u{F568}", "\u{F569}", "\u{F56A}", "\u{F56B}", "\u{F56C}", "\u{F56D}", "\u{F56E}", "\u{F56F}", "\u{F570}", "\u{F571}", "\u{F572}", "\u{F573}", "\u{F574}", "\u{F575}", "\u{F576}", "\u{F577}", "\u{F578}", "\u{F60F}", "\u{F610}", "\u{F579}", "\u{F57A}", "\u{F57B}", "\u{F57C}", "\u{F5CB}", "\u{F57D}", "\u{F57E}", "\u{F57F}", "\u{F580}", "\u{F581}", "\u{F582}", "\u{F583}", "\u{F584}", "\u{F585}", "\u{F586}", "\u{F587}", "\u{F588}", "\u{F589}", "\u{F58A}", "\u{F58B}", "\u{F6B0}", "\u{F58C}", "\u{F58D}", "\u{F58E}", "\u{F58F}", "\u{F612}", "\u{F590}", "\u{F591}", "\u{F592}", "\u{F593}", "\u{F67D}", "\u{F594}", "\u{F595}", "\u{F596}", "\u{F597}", "\u{F598}", "\u{F67E}", "\u{F599}", "\u{F59A}", "\u{F59B}", "\u{F59C}", "\u{F59D}", "\u{F59E}", "\u{F59F}", "\u{F5A0}", "\u{F62F}", "\u{F611}", "\u{F5A1}", "\u{F5A2}", "\u{F5A3}", "\u{F5A4}", "\u{F5A5}", "\u{F5A6}", "\u{F5A7}", "\u{F5A8}", "\u{F5A9}", "\u{F5AA}", "\u{F5AB}", "\u{F5AC}", "\u{F5AD}", "\u{F5AE}", "\u{F5AF}", "\u{F5B0}", "\u{F5B1}", "\u{F5B2}", "\u{F5B3}", "\u{F5B4}", "\u{F5B5}", "\u{F5B6}", "\u{F5B7}", "\u{F5B8}", "\u{F673}", "\u{F5B9}", "\u{F5BA}", "\u{F5BB}", "\u{F5BC}", "\u{F5BD}", "\u{F5BE}", "\u{F5BF}", "\u{F5C0}", "\u{F5C1}", "\u{F5C2}", "\u{F67F}", "\u{F5C3}", "\u{F5C4}"
    ]
}
